"""Checkpoints row (collapsed).

Transcribed verbatim from the original grafana-dashboard.json (panel indices 63-63).
"""

panels = [
    {
        "collapsed": True,
        "datasource": {"uid": "prometheus"},
        "gridPos": {"h": 1, "w": 24, "x": 0, "y": 56},
        "id": 293,
        "panels": [
            {
                "datasource": {"type": "prometheus", "uid": "${DS_PROMETHEUS}"},
                "description": "",
                "fieldConfig": {
                    "defaults": {
                        "color": {"mode": "palette-classic"},
                        "custom": {
                            "axisBorderShow": False,
                            "axisCenteredZero": False,
                            "axisColorMode": "text",
                            "axisLabel": "",
                            "axisPlacement": "auto",
                            "barAlignment": -1,
                            "drawStyle": "line",
                            "fillOpacity": 8,
                            "gradientMode": "none",
                            "hideFrom": {
                                "legend": False,
                                "tooltip": False,
                                "viz": False,
                            },
                            "insertNulls": False,
                            "lineInterpolation": "linear",
                            "lineWidth": 1,
                            "pointSize": 5,
                            "scaleDistribution": {"type": "linear"},
                            "showPoints": "never",
                            "spanNulls": True,
                            "stacking": {"group": "A", "mode": "none"},
                            "thresholdsStyle": {"mode": "off"},
                        },
                        "mappings": [],
                        "thresholds": {
                            "mode": "absolute",
                            "steps": [
                                {"color": "green"},
                                {"color": "red", "value": 80},
                            ],
                        },
                        "unit": "none",
                        "unitScale": True,
                    },
                    "overrides": [],
                },
                "gridPos": {"h": 6, "w": 5, "x": 0, "y": 57},
                "id": 295,
                "options": {
                    "legend": {
                        "calcs": [],
                        "displayMode": "list",
                        "placement": "bottom",
                        "showLegend": True,
                    },
                    "tooltip": {"mode": "multi", "sort": "none"},
                },
                "pluginVersion": "8.2.1",
                "targets": [
                    {
                        "datasource": {"type": "prometheus", "uid": "${DS_PROMETHEUS}"},
                        "exemplar": True,
                        "expr": '{__name__=~"cnpg_pg_stat_(bgwriter|checkpointer)_checkpoints_req",namespace=~"$namespace",pod=~"$instances"}',
                        "format": "time_series",
                        "hide": False,
                        "instant": False,
                        "interval": "",
                        "intervalFactor": 1,
                        "legendFormat": "req/{{pod}}",
                        "refId": "B",
                    },
                    {
                        "datasource": {"type": "prometheus", "uid": "${DS_PROMETHEUS}"},
                        "exemplar": True,
                        "expr": '{__name__=~"cnpg_pg_stat_(bgwriter|checkpointer)_checkpoints_timed",namespace=~"$namespace",pod=~"$instances"}',
                        "format": "time_series",
                        "interval": "",
                        "intervalFactor": 1,
                        "legendFormat": "timed/{{pod}}",
                        "refId": "A",
                    },
                ],
                "title": "Requested/Timed",
                "type": "timeseries",
            },
            {
                "datasource": {"type": "prometheus", "uid": "${DS_PROMETHEUS}"},
                "description": "",
                "fieldConfig": {
                    "defaults": {
                        "color": {"mode": "palette-classic"},
                        "custom": {
                            "axisBorderShow": False,
                            "axisCenteredZero": False,
                            "axisColorMode": "text",
                            "axisLabel": "",
                            "axisPlacement": "auto",
                            "barAlignment": -1,
                            "drawStyle": "line",
                            "fillOpacity": 8,
                            "gradientMode": "none",
                            "hideFrom": {
                                "legend": False,
                                "tooltip": False,
                                "viz": False,
                            },
                            "insertNulls": False,
                            "lineInterpolation": "linear",
                            "lineWidth": 1,
                            "pointSize": 5,
                            "scaleDistribution": {"type": "linear"},
                            "showPoints": "never",
                            "spanNulls": True,
                            "stacking": {"group": "A", "mode": "none"},
                            "thresholdsStyle": {"mode": "off"},
                        },
                        "mappings": [],
                        "thresholds": {
                            "mode": "absolute",
                            "steps": [
                                {"color": "green"},
                                {"color": "red", "value": 80},
                            ],
                        },
                        "unit": "ms",
                        "unitScale": True,
                    },
                    "overrides": [],
                },
                "gridPos": {"h": 6, "w": 5, "x": 5, "y": 57},
                "id": 296,
                "options": {
                    "legend": {
                        "calcs": [],
                        "displayMode": "list",
                        "placement": "bottom",
                        "showLegend": True,
                    },
                    "tooltip": {"mode": "multi", "sort": "none"},
                },
                "pluginVersion": "8.2.1",
                "targets": [
                    {
                        "datasource": {"type": "prometheus", "uid": "${DS_PROMETHEUS}"},
                        "exemplar": True,
                        "expr": '{__name__=~"cnpg_pg_stat_(bgwriter_checkpoint|checkpointer)_write_time",namespace=~"$namespace",pod=~"$instances"}',
                        "format": "time_series",
                        "hide": False,
                        "instant": False,
                        "interval": "",
                        "intervalFactor": 1,
                        "legendFormat": "write/{{pod}}",
                        "refId": "B",
                    },
                    {
                        "datasource": {"type": "prometheus", "uid": "${DS_PROMETHEUS}"},
                        "exemplar": True,
                        "expr": '{__name__=~"cnpg_pg_stat_(bgwriter_checkpoint|checkpointer)_sync_time",namespace=~"$namespace",pod=~"$instances"}',
                        "format": "time_series",
                        "interval": "",
                        "intervalFactor": 1,
                        "legendFormat": "sync/{{pod}}",
                        "refId": "A",
                    },
                ],
                "title": "Write/Sync time",
                "type": "timeseries",
            },
        ],
        "targets": [{"datasource": {"uid": "prometheus"}, "refId": "A"}],
        "title": "Checkpoints",
        "type": "row",
    }
]
